---
# tasks file for ansible-role-nginx/
- name: install nginx
  apt:
    name:   nginx
    state:  latest

- name: nginx service state
  service:
    name:     nginx
    state:    started
    enabled:  yes
